{"name": "test_auth_invalid_data", "status": "passed", "description": "\n        Steps\n        1. Open main page\n        2. Auth with invalid data\n        3. Check auth result\n        ", "attachments": [{"name": "log", "source": "58c22817-1b52-47dc-9ed7-55aca777e572-attachment.txt", "type": "text/plain"}], "start": 1631105320657, "stop": 1631105321229, "uuid": "2937b171-3e2d-499b-9c74-27d37cf3f93d", "historyId": "695f55378f8fe30fa2f217e0f6c38726", "testCaseId": "3288b5f502ddd6e63bc2e3b025925971", "fullName": "tests.auth.test_auth.TestAuth#test_auth_invalid_data", "labels": [{"name": "feature", "value": "authorisation"}, {"name": "story", "value": "проверка на ввод несуществующего пользователя"}, {"name": "tag", "value": "authorisation"}, {"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "PC-kashpovski"}, {"name": "thread", "value": "16036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_auth"}]}