{"name": "test_auth_empty_data[login]", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'", "trace": "self = <auth.test_auth.TestAuth object at 0x00000215FEFDCD30>, app = <pages.application.Application object at 0x00000215FE5CF430>, field = 'login'\n\n    @allure.feature(\"authorisation\")\n    @allure.story(\"проверка на ввод пустых полей\")\n    @pytest.mark.parametrize(\"field\", [\"login\", \"password\"])\n    def test_auth_empty_data(self, app, field):\n        \"\"\"\n        Steps\n        1. Open main page\n        2. Auth with empty data\n        3. Check auth result\n        \"\"\"\n        app.open_auth_page()\n        data = AuthData.random()\n        setattr(data, field, None)\n        app.login.auth(data)\n        with allure.step(\"Делаем скриншот\"):\n>           allure.attach(app.login.auth(data), name=\"Screenshot_none_data\", attachment_type=AttachmentType.PNG)\n\ntests\\auth\\test_auth.py:56: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_commons\\_allure.py:179: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_pytest\\listener.py:222: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_commons\\reporter.py:119: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_commons.logger.AllureFileLogger object at 0x00000215FE4A17C0>, body = None, file_name = 'fd54512e-e725-4e1f-99c1-382d5e9f7891-attachment.png'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = os.path.join(self._report_dir, file_name)\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, text_type):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'NoneType'\n\nc:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_commons\\logger.py:62: TypeError"}, "description": "\n        Steps\n        1. Open main page\n        2. Auth with empty data\n        3. Check auth result\n        ", "steps": [{"name": "Делаем скриншот", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"D:\\Ksenia\\QA\\Innopolis\\Auto_QA_Python\\Lesson_34-35\\test_moodle_project\\tests\\auth\\test_auth.py\", line 56, in test_auth_empty_data\n    allure.attach(app.login.auth(data), name=\"Screenshot_none_data\", attachment_type=AttachmentType.PNG)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_pytest\\listener.py\", line 222, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_commons\\reporter.py\", line 119, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_commons\\logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": "Screenshot_none_data", "source": "fd54512e-e725-4e1f-99c1-382d5e9f7891-attachment.png", "type": "image/png"}], "start": 1630746385353, "stop": 1630746385791}], "attachments": [{"name": "log", "source": "fc3223ed-985d-4d44-96a3-447ee12bdea9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "field", "value": "'login'"}], "start": 1630746384800, "stop": 1630746385792, "uuid": "dfc799c5-ea1e-4859-8119-7bdd556fd185", "historyId": "473ff3d1c17b25620fdc6f1c5ed02344", "testCaseId": "8c5131fa66dd3efd0c7e051319675cf7", "fullName": "tests.auth.test_auth.TestAuth#test_auth_empty_data", "labels": [{"name": "feature", "value": "authorisation"}, {"name": "story", "value": "проверка на ввод пустых полей"}, {"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "PC-kashpovski"}, {"name": "thread", "value": "31324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_auth"}]}